/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiHiringRouteImport } from './routes/ai-hiring'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as HireLatamAccountantsRouteImport } from './routes/hire-latam-accountants'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as EsIndexRouteImport } from './routes/es/index'
import { Route as EsAiHiringRouteImport } from './routes/es/ai-hiring'
import { Route as EsConnectRouteImport } from './routes/es/connect'
import { Route as EsHireLatamAccountantsRouteImport } from './routes/es/hire-latam-accountants'
import { Route as EsHowItWorksRouteImport } from './routes/es/how-it-works'
import { Route as EsJobsRouteImport } from './routes/es/jobs'
import { Route as EsPricingRouteImport } from './routes/es/pricing'
import { Route as EsPrivacyRouteImport } from './routes/es/privacy'
import { Route as EsTermsRouteImport } from './routes/es/terms'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiHiringRoute = AiHiringRouteImport.update({
  id: '/ai-hiring',
  path: '/ai-hiring',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const HireLatamAccountantsRoute = HireLatamAccountantsRouteImport.update({
  id: '/hire-latam-accountants',
  path: '/hire-latam-accountants',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const EsIndexRoute = EsIndexRouteImport.update({
  id: '/es/',
  path: '/es/',
  getParentRoute: () => rootRouteImport,
} as any)
const EsAiHiringRoute = EsAiHiringRouteImport.update({
  id: '/es/ai-hiring',
  path: '/es/ai-hiring',
  getParentRoute: () => rootRouteImport,
} as any)
const EsConnectRoute = EsConnectRouteImport.update({
  id: '/es/connect',
  path: '/es/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const EsHireLatamAccountantsRoute = EsHireLatamAccountantsRouteImport.update({
  id: '/es/hire-latam-accountants',
  path: '/es/hire-latam-accountants',
  getParentRoute: () => rootRouteImport,
} as any)
const EsHowItWorksRoute = EsHowItWorksRouteImport.update({
  id: '/es/how-it-works',
  path: '/es/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const EsJobsRoute = EsJobsRouteImport.update({
  id: '/es/jobs',
  path: '/es/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const EsPricingRoute = EsPricingRouteImport.update({
  id: '/es/pricing',
  path: '/es/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const EsPrivacyRoute = EsPrivacyRouteImport.update({
  id: '/es/privacy',
  path: '/es/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const EsTermsRoute = EsTermsRouteImport.update({
  id: '/es/terms',
  path: '/es/terms',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-hiring': typeof AiHiringRoute
  '/connect': typeof ConnectRoute
  '/hire-latam-accountants': typeof HireLatamAccountantsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/jobs': typeof JobsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/es/ai-hiring': typeof EsAiHiringRoute
  '/es/connect': typeof EsConnectRoute
  '/es/hire-latam-accountants': typeof EsHireLatamAccountantsRoute
  '/es/how-it-works': typeof EsHowItWorksRoute
  '/es/jobs': typeof EsJobsRoute
  '/es/pricing': typeof EsPricingRoute
  '/es/privacy': typeof EsPrivacyRoute
  '/es/terms': typeof EsTermsRoute
  '/es/': typeof EsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-hiring': typeof AiHiringRoute
  '/connect': typeof ConnectRoute
  '/hire-latam-accountants': typeof HireLatamAccountantsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/jobs': typeof JobsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/es/ai-hiring': typeof EsAiHiringRoute
  '/es/connect': typeof EsConnectRoute
  '/es/hire-latam-accountants': typeof EsHireLatamAccountantsRoute
  '/es/how-it-works': typeof EsHowItWorksRoute
  '/es/jobs': typeof EsJobsRoute
  '/es/pricing': typeof EsPricingRoute
  '/es/privacy': typeof EsPrivacyRoute
  '/es/terms': typeof EsTermsRoute
  '/es': typeof EsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-hiring': typeof AiHiringRoute
  '/connect': typeof ConnectRoute
  '/hire-latam-accountants': typeof HireLatamAccountantsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/jobs': typeof JobsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/es/ai-hiring': typeof EsAiHiringRoute
  '/es/connect': typeof EsConnectRoute
  '/es/hire-latam-accountants': typeof EsHireLatamAccountantsRoute
  '/es/how-it-works': typeof EsHowItWorksRoute
  '/es/jobs': typeof EsJobsRoute
  '/es/pricing': typeof EsPricingRoute
  '/es/privacy': typeof EsPrivacyRoute
  '/es/terms': typeof EsTermsRoute
  '/es/': typeof EsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-hiring'
    | '/connect'
    | '/hire-latam-accountants'
    | '/how-it-works'
    | '/jobs'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/es/ai-hiring'
    | '/es/connect'
    | '/es/hire-latam-accountants'
    | '/es/how-it-works'
    | '/es/jobs'
    | '/es/pricing'
    | '/es/privacy'
    | '/es/terms'
    | '/es/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-hiring'
    | '/connect'
    | '/hire-latam-accountants'
    | '/how-it-works'
    | '/jobs'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/es/ai-hiring'
    | '/es/connect'
    | '/es/hire-latam-accountants'
    | '/es/how-it-works'
    | '/es/jobs'
    | '/es/pricing'
    | '/es/privacy'
    | '/es/terms'
    | '/es'
  id:
    | '__root__'
    | '/'
    | '/ai-hiring'
    | '/connect'
    | '/hire-latam-accountants'
    | '/how-it-works'
    | '/jobs'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/es/ai-hiring'
    | '/es/connect'
    | '/es/hire-latam-accountants'
    | '/es/how-it-works'
    | '/es/jobs'
    | '/es/pricing'
    | '/es/privacy'
    | '/es/terms'
    | '/es/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiHiringRoute: typeof AiHiringRoute
  ConnectRoute: typeof ConnectRoute
  HireLatamAccountantsRoute: typeof HireLatamAccountantsRoute
  HowItWorksRoute: typeof HowItWorksRoute
  JobsRoute: typeof JobsRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  EsAiHiringRoute: typeof EsAiHiringRoute
  EsConnectRoute: typeof EsConnectRoute
  EsHireLatamAccountantsRoute: typeof EsHireLatamAccountantsRoute
  EsHowItWorksRoute: typeof EsHowItWorksRoute
  EsJobsRoute: typeof EsJobsRoute
  EsPricingRoute: typeof EsPricingRoute
  EsPrivacyRoute: typeof EsPrivacyRoute
  EsTermsRoute: typeof EsTermsRoute
  EsIndexRoute: typeof EsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-hiring': {
      id: '/ai-hiring'
      path: '/ai-hiring'
      fullPath: '/ai-hiring'
      preLoaderRoute: typeof AiHiringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire-latam-accountants': {
      id: '/hire-latam-accountants'
      path: '/hire-latam-accountants'
      fullPath: '/hire-latam-accountants'
      preLoaderRoute: typeof HireLatamAccountantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/': {
      id: '/es/'
      path: '/es'
      fullPath: '/es/'
      preLoaderRoute: typeof EsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/ai-hiring': {
      id: '/es/ai-hiring'
      path: '/es/ai-hiring'
      fullPath: '/es/ai-hiring'
      preLoaderRoute: typeof EsAiHiringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/connect': {
      id: '/es/connect'
      path: '/es/connect'
      fullPath: '/es/connect'
      preLoaderRoute: typeof EsConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/hire-latam-accountants': {
      id: '/es/hire-latam-accountants'
      path: '/es/hire-latam-accountants'
      fullPath: '/es/hire-latam-accountants'
      preLoaderRoute: typeof EsHireLatamAccountantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/how-it-works': {
      id: '/es/how-it-works'
      path: '/es/how-it-works'
      fullPath: '/es/how-it-works'
      preLoaderRoute: typeof EsHowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/jobs': {
      id: '/es/jobs'
      path: '/es/jobs'
      fullPath: '/es/jobs'
      preLoaderRoute: typeof EsJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/pricing': {
      id: '/es/pricing'
      path: '/es/pricing'
      fullPath: '/es/pricing'
      preLoaderRoute: typeof EsPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/privacy': {
      id: '/es/privacy'
      path: '/es/privacy'
      fullPath: '/es/privacy'
      preLoaderRoute: typeof EsPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/terms': {
      id: '/es/terms'
      path: '/es/terms'
      fullPath: '/es/terms'
      preLoaderRoute: typeof EsTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiHiringRoute: AiHiringRoute,
  ConnectRoute: ConnectRoute,
  HireLatamAccountantsRoute: HireLatamAccountantsRoute,
  HowItWorksRoute: HowItWorksRoute,
  JobsRoute: JobsRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  EsAiHiringRoute: EsAiHiringRoute,
  EsConnectRoute: EsConnectRoute,
  EsHireLatamAccountantsRoute: EsHireLatamAccountantsRoute,
  EsHowItWorksRoute: EsHowItWorksRoute,
  EsJobsRoute: EsJobsRoute,
  EsPricingRoute: EsPricingRoute,
  EsPrivacyRoute: EsPrivacyRoute,
  EsTermsRoute: EsTermsRoute,
  EsIndexRoute: EsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
